#!/usr/bin/env python3

##########################################
#
#    Coded by Eugene Cormier
#         May-Oct 2017
#
# Written to fill the gaping hole in the
#     Linux ecosystem, namely a nice
#     commandline countdown timer
#
# you need the following for this script
#   to work:
#               ogg123
##########################################

##################################################
# IMPORTS
##################################################
from sys import argv
from time import sleep
from subprocess import call
from os import devnull

audiocommand = 'ogg123'
audiofile = '/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga'

##################################################
# FUNCTIONS
##################################################

def noargsthenbail():
    if len(argv)==1:
        # this needs to be changed to be more informative
        print('No arguments')
        exit(1)

def parsearguments():
    userinput = argv[1]
    timervalue = []
    # hours
    if userinput[-1] == 'H':
        if len(userinput) == 3:
            timervalue.append(userinput[0:len(userinput)-1])
        else:
            timervalue.append('0' + userinput[0:len(userinput)-1])
    else:
        timervalue.append('00')
    # minutes
    if userinput[-1] == 'M':
        if len(userinput) == 3:
            timervalue.append(userinput[0:len(userinput)-1])
        else:
            timervalue.append('0' + userinput[0:len(userinput)-1])
    else:
        timervalue.append('00')
    # seconds
    if userinput[-1] == 'S':
        if len(userinput) == 3:
            timervalue.append(userinput[0:len(userinput)-1])
        else:
            timervalue.append('0' + userinput[0:len(userinput)-1])
    else:
        timervalue.append('00')
    return timervalue

def seconds(timervalue):
  temp = timervalue[2]
  temp = int(temp) - 1
  if len(str(temp)) == 2:
    timervalue[2] = temp
  else:
    timervalue[2] = '0' + str(temp)
  print('\rCountDown Timer: ' + str(timervalue[0]) + ':' + str(timervalue[1]) + ':' + str(timervalue[2]) + "    " , end="" )

def minutes(timervalue):
  temp = timervalue[1]
  temp = int(temp) - 1
  if len(str(temp)) == 2:
    timervalue[1] = temp
  else:
    timervalue[1] = '0' + str(temp)
  timervalue[2] = 60

def hours(timervalue):
  temp = timervalue[0]
  temp = int(temp) - 1
  if len(str(temp)) == 2:
    timervalue[0] = temp
  else:
    timervalue[0] = '0' + str(temp)
  timervalue[1] = 60

def runtimer(timervalue):
  while True:
    if timervalue[2] != '00': # if seconds value is set
      seconds(timervalue)
      sleep(1)
    else: # if seconds are at 00
      if timervalue[1] != '00': # if minutes value is set
        minutes(timervalue)
      else: # if minutes are at 00
        if timervalue[0] != '00': # if hours value is set
          hours(timervalue)
        else:
          break
        pass
      pass

def soundandbreak(audiofile):
  try:
    print("\rCountDown Timer: 00:00:00  --> Countdown Complete, press 'ctrl + c' to exit   " , end="" )
    while True:
      # stderr=nowhere: don't echo audio command output to term
      nowhere = open(devnull, 'w')
      call([audiocommand, audiofile], stderr=nowhere)
  except KeyboardInterrupt:
    pass

def main():
    noargsthenbail()
    totaltime = parsearguments()
    runtimer(totaltime)
    soundandbreak(audiofile)

main()
